.PHONY: clean All

All:
	@echo "----------Building project:[ image - Debug ]----------"
	@cd "image" && "$(MAKE)" -f  "image.mk"
clean:
	@echo "----------Cleaning project:[ image - Debug ]----------"
	@cd "image" && "$(MAKE)" -f  "image.mk" clean
